project:
  type: website

website:
  title: "Jeremy Thomas"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: projects.qmd
        text: Projects

format:
  html:
    theme: mintly
    css: styles.css
